version: '3.3'
services:
  rproxy: 
    image: nginx:latest
    container_name: nginx_rproxy
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/data/www   
    ports:
      - 8088:8088
  myservice:
    build:
      context: ./api
      dockerfile: Dockerfile-uwsgi
    container_name: myservice   
    ports:
      - '5000:5000'
  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: nodejs  
    ports:
      - '8081:8081'
  quarkus_demo_jvm:
    build:
      context: ./quarkus-demo/src/main/docker
      dockerfile: Dockerfile.jvm
    container_name: quarkus_demo_jvm 
    ports:
      - '8082:8082'
  quarkus_demo_native:
    build:
      context: ./quarkus-demo/src/main/docker
      dockerfile: Dockerfile.native
    container_name: quarkus_demo_native  
    ports:
      - '8083:8083'