FROM python:3-alpine

RUN apk update
RUN apk add py-pip
RUN apk add --no-cache --virtual .build-deps gcc linux-headers libc-dev
RUN pip install --upgrade pip

WORKDIR /app
COPY . /app

RUN pip --no-cache-dir install -r requirements.txt
RUN apk del .build-deps
CMD ["uwsgi", "myuwsgi.ini"]

#ENTRYPOINT ["uwsgi", "--ini-paste", "/app/myuwsgi.ini" ]